module.exports = {
  MID: process.env.MID,
  PAYTM_MERCHANT_KEY: process.env.PAYTM_MERCHANT_KEY,
  PAYTM_FINAL_URL: process.env.PAYTM_FINAL_URL,
  WEBSITE: process.env.WEBSITE,
  CHANNEL_ID: process.env.CHANNEL_ID,
  INDUSTRY_TYPE_ID: process.env.INDUSTRY_TYPE_ID,
  CALLBACK_URL: process.env.CALLBACK_URL,
  FIREBASE_API_KEY: process.env.FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN: process.env.FIREBASE_AUTH_DOMAIN,
  FIREBASE_DATABASE_URL: process.env.FIREBASE_DATABASE_URL,
  FIREBASE_PROJECT_ID: process.env.FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET: process.env.FIREBASE_STORAGE_BUCKET,
  FIREBASE_MESSAGING_SENDER_ID: process.env.FIREBASE_MESSAGING_SENDER_ID,
  FIREBASE_APP_ID: process.env.FIREBASE_APP_ID,
  FIREBASE_MEASUREMENT_ID: process.env.FIREBASE_MEASUREMENT_ID,
  SENDGRID_API_KEY:process.env.SENDGRID_API_KEY
};
